### ISSUE TITLE
inline post issue at restart runs with gnu compiler

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/ufsatm#320]
## Description
The GFS restart run failed with gnu compiler. The error is reported in post_gfs.F90 where the association of a pointer needs to be checked before get the size of the pointer. An fix is required to make the code run with gnu compiler. 

### To Reproduce:
What compilers/machines are you seeing this with? GNU compiler
Give explicit steps to reproduce the behavior.
1. Run the control restart test with gnu compiler and with inline post turned on 
2. The run failed with error: 
144: Backtrace for this error:
144: #0  0x2ad93029744f in ???
144: #1  0x13aca47 in __post_gfs_MOD_post_run_gfs
144:    at /scratch1/NCEPDEV/nems/Jun.Wang/nems/vlab/20210519/gnu/ufs-weather-model/FV3/io/post_gfs.F90:161

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. 
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. 

- associated [ufs-weather-model/pull/<561>](https://github.com/ufs-community/ufs-weather-model/pull/561)

**Comment by junwang-noaa** [comment]
The issue is fixed in fv3atm PR#321, close issue.
